/**
 * prisma.js — one Prisma client, its lifecycle, and the soft-delete rule.
 *
 * The client is the one generated by `@foodora/database`. The backend has no
 * schema of its own and never will: BACKEND-REQUIREMENTS is explicit that there
 * is one finalised datamodel and a second copy of it is a bug waiting to
 * diverge. `bun run generate` in `database/` writes the client; this reads it.
 *
 * Three things happen here and nowhere else:
 *
 *  1. **Connection.** Opened during boot, so a database that is down is a
 *     start-up failure with a clear message rather than a 500 on the first
 *     request. Closed on `onClose`, so a `SIGTERM` returns the pool.
 *  2. **Soft delete.** `main.prisma` §3: `deletedAt IS NULL` means active, and
 *     nothing in PostgreSQL enforces it. The extension below rewrites reads to
 *     add the filter and turns `delete` into an update, for the models that have
 *     the column — which it discovers from the generated schema rather than a
 *     list somebody has to maintain.
 *  3. **Readiness.** `checkDatabase()` — a real query, with a deadline.
 */
import fp from "fastify-plugin";
import { PrismaClient, Prisma } from "@foodora/database";
import env from "../config/env.js";

/**
 * Models carrying `deletedAt`, from the generated schema.
 *
 * Derived rather than listed: the immutable financial tables (payments, ledger
 * entries, order events, dispatches) deliberately have no `deletedAt` — they are
 * never deleted, only superseded — and a hand-kept list would eventually filter
 * on a column one of them does not have, which is a runtime error on a query
 * that used to work.
 */
export const SOFT_DELETE_MODELS = new Set(
  Prisma.dmmf.datamodel.models
    .filter((model) => model.fields.some((field) => field.name === "deletedAt"))
    .map((model) => model.name),
);

const READ_OPERATIONS = new Set([
  "findUnique",
  "findUniqueOrThrow",
  "findFirst",
  "findFirstOrThrow",
  "findMany",
  "count",
  "aggregate",
  "groupBy",
]);

/**
 * Add `deletedAt: null` to a read, and turn a delete into one.
 *
 * Two limits, both stated rather than hidden, because a silent one would be
 * worse than the bug it papers over:
 *
 *  - **Relations loaded through `include`/`select` are not filtered.** A query
 *    extension sees the top-level model only. A route that includes a relation
 *    whose rows can be soft-deleted filters it in the `include` itself:
 *    `include: { branches: { where: { deletedAt: null } } }`.
 *  - **`update` and `updateMany` are left alone.** Restoring a row means writing
 *    `deletedAt: null` to a row that is currently deleted, and a filter here
 *    would make that impossible.
 *
 * `findUnique` is filtered by merging into `where`, which Prisma 5+ allows
 * alongside the unique field. That is the case that matters most: a deleted
 * vendor fetched by id and rendered is exactly the leak §3 is about.
 */
export function softDeleteExtension(unextended) {
  return Prisma.defineExtension({
    name: "foodora-soft-delete",
    query: {
      $allModels: {
        async $allOperations({ model, operation, args, query }) {
          if (!SOFT_DELETE_MODELS.has(model)) return query(args);

          if (READ_OPERATIONS.has(operation)) {
            return query({ ...args, where: { ...(args.where ?? {}), deletedAt: null } });
          }

          if (operation === "delete" || operation === "deleteMany") {
            throw new Error(
              `${model}.${operation}() is disabled: ${model} is soft-deleted. ` +
                "Write `deletedAt` with `update`/`updateMany`, or use `prisma.$unfiltered` " +
                "when a row genuinely has to leave the database.",
            );
          }

          return query(args);
        },
      },
    },
    client: {
      /**
       * The unextended client — deleted rows included, `delete` real.
       *
       * Needed by three callers and no others: a restore, an admin export that
       * has to show what was removed, and the hard delete a retention policy
       * eventually performs. Naming it `$unfiltered` at the call site is the
       * point: the exception is visible in the diff.
       */
      $unfiltered() {
        return unextended;
      },
    },
  });
}

async function prismaPlugin(fastify) {
  const base = new PrismaClient({
    datasources: { db: { url: env.databaseUrl } },
    // Prisma's own logs, routed into Fastify's logger so there is one log stream.
    log: [
      { level: "warn", emit: "event" },
      { level: "error", emit: "event" },
      ...(env.isDevelopment ? [{ level: "query", emit: "event" }] : []),
    ],
  });

  base.$on("warn", (event) => fastify.log.warn({ prisma: event }, "prisma warning"));
  base.$on("error", (event) => fastify.log.error({ prisma: event }, "prisma error"));
  if (env.isDevelopment) {
    base.$on("query", (event) =>
      fastify.log.debug({ query: event.query, params: event.params, durationMs: event.duration }, "prisma query"),
    );
  }

  const prisma = base.$extends(softDeleteExtension(base));

  try {
    await base.$connect();
  } catch (error) {
    fastify.log.error({ err: error }, "could not connect to PostgreSQL");
    await base.$disconnect().catch(() => {});
    throw error;
  }

  fastify.decorate("prisma", prisma);

  /**
   * Is the database actually answering?
   *
   * `$connect()` succeeding is not the same question — a pool can be open onto a
   * server that has since stopped accepting queries — so this runs a real one,
   * and it runs it with a deadline. Without the deadline a readiness probe on a
   * hung connection never answers at all, and "no response" is the one thing a
   * load balancer cannot act on.
   */
  fastify.decorate("checkDatabase", async () => {
    const started = process.hrtime.bigint();
    const timeout = new Promise((_, reject) =>
      setTimeout(
        () => reject(new Error(`database health check timed out after ${env.databaseHealthTimeoutMs}ms`)),
        env.databaseHealthTimeoutMs,
      ).unref(),
    );

    try {
      await Promise.race([base.$queryRaw`SELECT 1`, timeout]);
      return { ok: true, latencyMs: Number(process.hrtime.bigint() - started) / 1e6 };
    } catch (error) {
      return { ok: false, latencyMs: Number(process.hrtime.bigint() - started) / 1e6, error: error.message };
    }
  });

  fastify.addHook("onClose", async (instance) => {
    instance.log.info("disconnecting from PostgreSQL");
    await base.$disconnect();
  });
}

export default fp(prismaPlugin, { name: "prisma" });
